name: yolov4-metal

dependencies:
  - python==3.10
  - pip
  - matplotlib
  - opencv
  - pip:
    - opencv-python==4.1.1.26
    - lxml
    - tqdm
    - tensorflow==2.10.0rc0
    - absl-py
    - easydict
    - pillow
    - scipy